#!/usr/bin/python

# Fake apt-cache python script to emulate policy output for test usage

# Python3-compatible print() function
from __future__ import print_function

import sys
import os

if len(sys.argv) <= 1 or sys.argv[1] != 'policy':
	sys.exit("Shall only be run with exactly one argument: 'policy'")

print("Package files:")
print(" 100 /var/lib/dpkg/status")
print("     release a=now")

if os.environ.get('TEST_APT_CACHE1') == '132':
	print(' 132 http://Mirror_is_not_read/folder-either-debian/ sid/main arch Packages')
	print('     release o=oRigIn,a=SuiTe,n=codename-not-read,l=lABel,c=C0mp0nent')
	print('     origin Mirror-is-not-read')

if os.environ.get('TEST_APT_CACHE2') == '35':
	print(' 35  http://MirRor_is_not_read/folder-either-debian/ sid/main arch Packages')
	print('     release o=0RigIn,a=5uiTe,n=codename-not-read,l=1ABel,c=C03p0nent')
	print('     origin MirRor-is-not-read')
