#!/bin/sh -e

. /usr/share/debconf/confmodule

if [ ! -e /etc/shadow ]; then
    db_get lsb/shadowconfig
    if [ "$RET" = "true" ]; then
        /usr/sbin/shadowconfig on >&2 || true
    fi
fi

##DEBHELPER##
