#!/bin/sh -e

remove_ldso_symlink () {
    ARCH=`dpkg --print-installation-architecture`
    case "$ARCH" in
        s390|ia64|ppc64)
            rm -f /lib/ld-lsb-$ARCH.so.[12]
            ;;
        powerpc)
            rm -f /lib/ld-lsb-ppc32.so.[12]
            ;;
        i386)
            rm -f /lib/ld-lsb.so.[12]
            ;;
        amd64)
            rm -f /lib/ld-lsb.so.[12] /lib64/ld-lsb-x86-64.so.2
            ;;
        *)
            echo "ld-lsb-*.so.1 symlink for $ARCH is unknown; not removed."
            ;;
    esac
}

PATH=/sbin:/usr/sbin:$PATH
export PATH

case "$1" in
    remove)
        remove_ldso_symlink
        rm -f /var/lib/lsb/facilities
        rm -f /var/lib/lsb/depends
        ;;
    failed-upgrade|upgrade|deconfigure)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#
